### ISSUE TITLE
OSX Issue: terminating with uncaught exception

### ISSUE THREAD

**Issue by VictorYudin** [imageworks/OpenShadingLanguage#405]
Hello everyone.

I have OSX 10.9.4 and following libraries:
- boost 1.56,
- LLVM 3.4.2 with option --disable-terminfo,
- OpenImageIO 1.5.2dev 881987ee5f with options BUILDSTATIC=1 LINKSTATIC=1,
- OpenShadingLanguage 1.5.10 cbbdf6fead with options BUILDSTATIC=1 LINKSTATIC=1 LLVM_STATIC=1

The issue can be easily reproducible with testshade and testrender. For example when I run testshade I have following error message:

```
libc++abi.dylib: terminating with uncaught exception of type boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::lock_error> >
Abort trap: 6
```

bt looks like this:

```
(gdb) bt
#0  0x00007fff95ae9866 in __pthread_kill ()
#1  0x00007fff9718535c in pthread_kill ()
#2  0x00007fff8d9a7b1a in abort ()
#3  0x00007fff93fedf31 in abort_message ()
#4  0x00007fff94013952 in default_terminate_handler ()
#5  0x00007fff8f889322 in _objc_terminate ()
#6  0x00007fff940111d1 in std::__terminate ()
#7  0x00007fff94010c5b in __cxa_throw ()
#8  0x0000000100013877 in boost::throw_exception<boost::lock_error> (e=@0x7fff5fbfb158) at throw_exception.hpp:69
#9  0x0000000100014ea3 in boost::mutex::lock (this=0x1016bc460) at mutex.hpp:119
#10 0x0000000100016ae3 in lock_guard (this=0x7fff5fbfb248, m_=@0x1016bc460) at lock_guard.hpp:38
#11 0x0000000100016a6d in lock_guard (this=0x7fff5fbfb248, m_=@0x1016bc460) at lock_guard.hpp:39
#12 0x0000000100925d7a in OpenImageIO::v1_5::pvt::ImageCacheImpl::purge_perthread_microcaches (this=0x103001e00) at /Users/victor/Development/OpenImageIO/src/libtexture/imagecache.cpp:2730
#13 0x0000000100927717 in OpenImageIO::v1_5::pvt::ImageCacheImpl::invalidate_all (this=0x103001e00, force=false) at /Users/victor/Development/OpenImageIO/src/libtexture/imagecache.cpp:2650
#14 0x00000001009205c5 in OpenImageIO::v1_5::pvt::ImageCacheImpl::attribute (this=0x103001e00, name=<value temporarily unavailable, due to optimizations>, type=<value temporarily unavailable, due to optimizations>, val=0x7fff5fbfc4f4) at /Users/victor/Development/OpenImageIO/src/libtexture/imagecache.cpp:1771
#15 0x00000001008f26a0 in OpenImageIO::v1_5::pvt::TextureSystemImpl::attribute (this=0x102803d70, name=<value temporarily unavailable, due to optimizations>, type=<value temporarily unavailable, due to optimizations>, val=0x7fff5fbfc4f4) at /Users/victor/Development/OpenImageIO/src/libtexture/texturesys.cpp:301
#16 0x000000010090243f in OpenImageIO::v1_5::pvt::TextureSystemImpl::attribute (this=0x102803d70, name=<value temporarily unavailable, due to optimizations>, val=1) at texture_pvt.h:72
#17 0x0000000100123006 in RendererServices (this=0x1016fcfe8, texsys=0x0) at /Users/victor/Development/OpenShadingLanguage/src/liboslexec/rendservices.cpp:65
#18 0x0000000100026709 in SimpleRenderer (this=0x1016fcfe8) at /Users/victor/Development/OpenShadingLanguage/src/testshade/simplerend.cpp:147
#19 0x00000001000266d5 in SimpleRenderer (this=0x1016fcfe8) at /Users/victor/Development/OpenShadingLanguage/src/testshade/simplerend.cpp:164
#20 0x000000010000edb4 in __cxx_global_var_init31 () at /Users/victor/Development/OpenShadingLanguage/src/testshade/testshade.cpp:84
#21 0x000000010000f0ba in global constructors keyed to a () at /Users/victor/Development/OpenShadingLanguage/src/testshade/testshade.cpp:354
#22 0x00007fff5fc11c2e in __dyld__ZN16ImageLoaderMachO18doModInitFunctionsERKN11ImageLoader11LinkContextE ()
#23 0x00007fff5fc11dba in __dyld__ZN16ImageLoaderMachO16doInitializationERKN11ImageLoader11LinkContextE ()
#24 0x00007fff5fc0ea62 in __dyld__ZN11ImageLoader23recursiveInitializationERKNS_11LinkContextEjRNS_21InitializerTimingListE ()
#25 0x00007fff5fc0e8f6 in __dyld__ZN11ImageLoader15runInitializersERKNS_11LinkContextERNS_21InitializerTimingListE ()
#26 0x00007fff5fc021da in __dyld__ZN4dyld24initializeMainExecutableEv ()
#27 0x00007fff5fc05560 in __dyld__ZN4dyld5_mainEPK12macho_headermiPPKcS5_S5_Pm ()
#28 0x00007fff5fc0127b in __dyld__ZN13dyldbootstrap5startEPK12macho_headeriPPKclS2_Pm ()
#29 0x00007fff5fc0105e in __dyld__dyld_start ()
```

It looks like boost's lock_guardboost::mutex throws EINVAL exception at mutex.hpp:119

Thanks for reading this. How is it possible to fix that?

**Comment by alobaidizt** [comment]
having a similar issue, were there any solutions to this? I'm open to debugging tips as well. : )

**Comment by lgritz** [comment]
@alobaidizt, What versions of OIIO, OSL, and Boost are involved?

**Comment by alobaidizt** [comment]
@lgritz Thanks for the quick response. I actually ended up resolving the issue. I was just not passing the needed arguments. Haha, it happens.

**Comment by lgritz** [comment]
OK, awesome.
As far as the original issue goes, every component is such an old version now, we should close the issue and re-open if it's a continued problem for anybody on modern versions.

**Comment by effolkronium** [comment]
Burn in hell. Why you didn't wrote the missing arguments?

**Comment by lgritz** [comment]
@effolkronium Are you encountering this same issue with a current version of OSL?
