### ISSUE TITLE
Failed to Run Any Shaders on Fedora 24

### ISSUE THREAD

**Issue by Shihira** [imageworks/OpenShadingLanguage#680]
Hi.

I compiled the latest commit with compatible package llvm34/llvm34-devel/llvm34-libs/llvm34-static privided by official fedora repo. No error during compilation, but literally ALL the tests failed. And also, using the output liboslexec to build a blender has no error, but blender crashes when trying to run some osl shaders.

It throws an exception and crashes down:

```
Couldn't find function osl_filterwidth_fdf
/home/shihira/Software/Blender/OpenShadingLanguage/src/liboslexec/llvm_util.cpp:1165: failed assertion 'func'
```

Here is the backtrace found by gdb, hope it helps.

```
(gdb) bt
#0  0x00007ffff17a86f5 in raise () at /lib64/libc.so.6
#1  0x00007ffff17aa2fa in abort () at /lib64/libc.so.6
#2  0x00007ffff7a91be0 in OSL::pvt::LLVM_Util::call_function(llvm::Value*, llvm::Value**, int) ()
    at /home/shihira/Software/Blender/OpenShadingLanguage/build/linux64/src/liboslexec/liboslexec.so
#3  0x00007ffff7a6276a in OSL::pvt::llvm_gen_filterwidth(OSL::pvt::BackendLLVM&, int) ()
    at /home/shihira/Software/Blender/OpenShadingLanguage/build/linux64/src/liboslexec/liboslexec.so
#4  0x00007ffff7a87236 in OSL::pvt::BackendLLVM::build_llvm_code(int, int, llvm::BasicBlock*) ()
    at /home/shihira/Software/Blender/OpenShadingLanguage/build/linux64/src/liboslexec/liboslexec.so
#5  0x00007ffff7a65317 in OSL::pvt::llvm_gen_functioncall(OSL::pvt::BackendLLVM&, int) ()
    at /home/shihira/Software/Blender/OpenShadingLanguage/build/linux64/src/liboslexec/liboslexec.so
#6  0x00007ffff7a87236 in OSL::pvt::BackendLLVM::build_llvm_code(int, int, llvm::BasicBlock*) ()
    at /home/shihira/Software/Blender/OpenShadingLanguage/build/linux64/src/liboslexec/liboslexec.so
#7  0x00007ffff7a6331a in OSL::pvt::llvm_gen_if(OSL::pvt::BackendLLVM&, int) ()
    at /home/shihira/Software/Blender/OpenShadingLanguage/build/linux64/src/liboslexec/liboslexec.so
#8  0x00007ffff7a87236 in OSL::pvt::BackendLLVM::build_llvm_code(int, int, llvm::BasicBlock*) ()
    at /home/shihira/Software/Blender/OpenShadingLanguage/build/linux64/src/liboslexec/liboslexec.so
#9  0x00007ffff7a8a202 in OSL::pvt::BackendLLVM::build_llvm_instance(bool) ()
    at /home/shihira/Software/Blender/OpenShadingLanguage/build/linux64/src/liboslexec/liboslexec.so
#10 0x00007ffff7a8b11c in OSL::pvt::BackendLLVM::run() ()
    at /home/shihira/Software/Blender/OpenShadingLanguage/build/linux64/src/liboslexec/liboslexec.so
#11 0x00007ffff799d006 in OSL::pvt::ShadingSystemImpl::optimize_group(OSL::ShaderGroup&) ()
    at /home/shihira/Software/Blender/OpenShadingLanguage/build/linux64/src/liboslexec/liboslexec.so
#12 0x00007ffff79badab in OSL::ShadingContext::execute_init(OSL::ShaderGroup&, OSL::ShaderGlobals&, bool) ()
    at /home/shihira/Software/Blender/OpenShadingLanguage/build/linux64/src/liboslexec/liboslexec.so
#13 0x00007ffff79bb644 in OSL::ShadingContext::execute(OSL::ShaderGroup&, OSL::ShaderGlobals&, bool) ()
    at /home/shihira/Software/Blender/OpenShadingLanguage/build/linux64/src/liboslexec/liboslexec.so
#14 0x000000000041204e in test_shade ()
#15 0x00007ffff1794731 in __libc_start_main () at /lib64/libc.so.6
#16 0x000000000040ccf9 in _start ()
```

This was when I tried to run `testshade` over the testsuite `asstep`.

I also have tried to build it with llvm35, which turns out to directly crash down with segmentation faults. I will supplement some log later.

Finally please allow me to thank you for your great job.

**Comment by Shihira** [comment]
```
$ ../runtest.py .
test source dir = ../../../../testsuite/aastep
command = ../../src/oslc/oslc test.osl >> out.txt 2>&1 ;
../../src/testshade/testshade -g 64 64 -od uint8 -o Cout out.tif test >> out.txt 2>&1 ;

/bin/sh: line 1:  5032 Segmentation fault      (core dumped) ../../src/testshade/testshade -g 64 64 -od uint8 -o Cout out.tif test >> out.txt 2>&1
#### Error: this command failed:  
../../src/testshade/testshade -g 64 64 -od uint8 -o Cout out.tif test >> out.txt 2>&1 
FAIL

$ gdb ../../src/testshade/testshade
...
(gdb) run -g 64 64 -od uint8 -o Cout out.tif test
Thread 1 "testshade" received signal SIGSEGV, Segmentation fault.
0x00007ffff345c52e in llvm::Twine::str[abi:cxx11]() const () from /usr/lib64/llvm35/libLLVM-3.5.so
(gdb) bt
#0  0x00007ffff345c52e in llvm::Twine::str[abi:cxx11]() const () at /usr/lib64/llvm35/libLLVM-3.5.so
#1  0x00007ffff34586be in llvm::Triple::Triple(llvm::Twine const&) () at /usr/lib64/llvm35/libLLVM-3.5.so
#2  0x00007ffff38da108 in llvm::EngineBuilder::create(llvm::TargetMachine*) () at /usr/lib64/llvm35/libLLVM-3.5.so
#3  0x00007ffff7a9134c in OSL::pvt::LLVM_Util::make_jit_execengine(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*) () at /home/shihira/Software/Blender/OpenShadingLanguage/build/linux64/src/liboslexec/liboslexec.so
#4  0x00007ffff7a8c2bf in OSL::pvt::BackendLLVM::run() ()
    at /home/shihira/Software/Blender/OpenShadingLanguage/build/linux64/src/liboslexec/liboslexec.so
#5  0x00007ffff799e096 in OSL::pvt::ShadingSystemImpl::optimize_group(OSL::ShaderGroup&) ()
    at /home/shihira/Software/Blender/OpenShadingLanguage/build/linux64/src/liboslexec/liboslexec.so
#6  0x00007ffff79bbe3b in OSL::ShadingContext::execute_init(OSL::ShaderGroup&, OSL::ShaderGlobals&, bool) ()
    at /home/shihira/Software/Blender/OpenShadingLanguage/build/linux64/src/liboslexec/liboslexec.so
#7  0x00007ffff79bc6d4 in OSL::ShadingContext::execute(OSL::ShaderGroup&, OSL::ShaderGlobals&, bool) ()
    at /home/shihira/Software/Blender/OpenShadingLanguage/build/linux64/src/liboslexec/liboslexec.so
#8  0x000000000041202e in test_shade ()
#9  0x00007ffff18e6731 in __libc_start_main () at /lib64/libc.so.6
#10 0x000000000040ccd9 in _start ()
```

I was running a test directly by executing runtest.py and testshade,  and the crash went like this.

**Comment by lgritz** [comment]
This issue references a version of LLVM that we no longer support. Closing.
